version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.1

    working_directory: ~/repo
    dependencies:
       pre:
       - wget https://releases.hashicorp.com/terraform/0.8.5/terraform_0.8.5_linux_386.zip
       - unzip terraform_0.8.5_linux_386.zip
       - sudo mv terraform /usr/local/bin/
       - chmod 777 /usr/local/bin/
       - export PATH=$PATH:/usr/local/bin/
       - source ~/.bashrc
       - terraform -v

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            wget https://releases.hashicorp.com/terraform/0.8.5/terraform_0.8.5_linux_386.zip
            unzip terraform_0.8.5_linux_386.zip
            sudo mv terraform /usr/local/bin/
            sudo chmod 777 /usr/local/bin/
            export PATH=$PATH:/usr/local/bin/
            source ~/.bashrc
            terraform -v
            echo "export PATH=$PATH:/usr/local/bin/" >> ~/.bash_profile
            pushd pipeline && terraform plan && terraform apply && popd


            
            



