version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.1

    working_directory: ~/repo
    dependencies:
       pre:
       - wget https://dl.bintray.com/mitchellh/terraform/terraform_0.6.3_linux_amd64.zip
       - unzip terraform_0.6.3_linux_amd64.zip

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            ./terraform apply terraform.plan
            ./terraform remote push
