version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.1

    working_directory: ~/repo
    dependencies:
       pre:
       - wget https://releases.hashicorp.com/terraform/0.10.0/terraform_0.10.0_linux_amd64.zip?_ga=2.240233731.1409573529.1502171270-1054727096.1502171270
       - mkdir ~/terra_code
       - cd ~/terra_code
       - unzip  terraform_0.10.0_linux_amd64.zip?_ga=2.240233731.1409573529.1502171270-1054727096.1502171270
       - export PATH=$PATH:~/terra_code/terraform

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            ./terraform apply terraform.plan
            ./terraform remote push
