version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04
      - image: python:3.6.0
    
    working_directory: ~/my-project

    steps:
      - checkout

      - run: command: echo 127.0.0.1 devhost | sudo tee -a /etc/hosts

dependencies:
  pre:
    - wget https://dl.bintray.com/mitchellh/terraform/terraform_0.6.3_linux_amd64.zip
    - unzip terraform_0.6.3_linux_amd64.zip
    
     
     - run:
	command: |
            set -xe
     	    sudo apt-get install -y unzip
	    
      # Deploy staging
      - deploy:
          command: |
          - ./terraform apply terraform.plan
          - ./terraform remote push     
      
