version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.1
      - image: hashicorp/terraform

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo
    dependencies:
       pre:
       - wget https://dl.bintray.com/mitchellh/terraform/terraform_0.6.3_linux_amd64.zip
       - unzip terraform_0.6.3_linux_amd64.zip

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
  
    
      - store_artifacts:
          path: test-reports
          destination: test-reports
    
  - deploy: 
          name: Deploy + Publish
          command: 
         - ./terraform apply terraform.plan
         - ./terraform remote push


