version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: python:3.6.0
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
      
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
	dependencies:
		pre:
		- wget https://dl.bintray.com/mitchellh/terraform/terraform_0.6.3_linux_amd64.zip
		- unzip terraform_0.6.3_linux_amd64.zip			
        - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
       - run:
          command: |
            . venv/bin/activate
            python manage.py test
       - store_artifacts:
          path: test-reports/
          destination: tr1
       - store_test_results:
          path: test-reports/
      
       - deploy:
          command: |
             - ./terraform apply terraform.plan
			       - ./terraform remote push
